import type { IconTypes } from "solid-icons";
import { BiLogosGit } from "solid-icons/bi";
import {
  FaBrandsDocker,
  FaBrandsGolang,
  FaBrandsJava,
  FaBrandsPython,
} from "solid-icons/fa";
import {
  SiApachejmeter,
  SiApachekafka,
  SiAstro,
  SiAzuredevops,
  SiCss3,
  SiDocker,
  SiDotnet,
  SiFigma,
  SiGit,
  SiHtml5,
  SiHyperledger,
  SiJavascript,
  SiJira,
  SiKubernetes,
  SiLinux,
  SiMicrosoftazure,
  SiMicrosoftsqlserver,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPowerbi,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRedux,
  SiSolid,
  SiSpringboot,
  SiSwift,
  SiTailwindcss,
  SiTypescript,
  SiVim,
  SiVuedotjs,
} from "solid-icons/si";

const SkillsFCs: IconTypes[] = [
  SiApachejmeter,
  SiApachekafka,
  SiAstro,
  SiAzuredevops,
  SiCss3,
  SiDocker,
  SiDotnet,
  SiFigma,
  SiGit,
  SiHtml5,
  SiHyperledger,
  SiJavascript,
  SiJira,
  SiKubernetes,
  SiLinux,
  SiMicrosoftazure,
  SiMicrosoftsqlserver,
  SiNextdotjs,
  SiNodedotjs,
  SiNumpy,
  SiPandas,
  SiPowerbi,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiRedux,
  SiSolid,
  SiSpringboot,
  SiSwift,
  SiTailwindcss,
  SiTypescript,
  SiVim,
  SiVuedotjs,
];

export const SkillsIcons = SkillsFCs.map((Icon) => (
  <Icon size={80} class="opacity-60 hover:opacity-80  transition-opacity" />
));
